source "https://rubygems.org"

gem "httparty", "~> 0.22.0"
gem "git", "~> 2.3", ">= 2.3.3"
gem "dotenv"
gem "terminal-table", "~> 4.0"
gem "ostruct"
gem "octokit", "~> 9.2"
gem "faraday-retry", "~> 2.2", ">= 2.2.1"
gem "midilib", "~> 4.0", ">= 4.0.2"