name: Daily Lumen Update

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Configure Git
        run: |
          git config --global user.name "Lumen"
          git config --global user.email "github-actions@github.com"
          
      - name: Make run script executable
        run: chmod +x ./run
          
      - name: Run Lumen using run script
        env:
          GITHUB_TOKEN: ${{ secrets.STATS }}
          WEATHER_TOKEN: ${{ secrets.WEATHER_API }}
        run: |
          # First make sure known_hosts has the GitHub key to avoid the prompt
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # Run your script using the ./run wrapper
          ./run